version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: sveltekit-postgres
    environment:
      POSTGRES_DB: guestbook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: unless-stopped

volumes:
  postgres_data:
